# investment portfolio

2021-06-15

In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

## Get YahooFinance stock ticker data as DataFrame

See: https://aroussi.com/post/python-yahoo-finance

In [2]:
#Interval required 1 minute
#data = yf.download(tickers='LBC-USD', period='1d', interval='1m')

In [3]:
#data

In [4]:
#type(data)

## Read stock portfolio csv to DataFrame

In [5]:
stocks = pd.read_csv('firstrade-positions-2021-06-15.csv', skipinitialspace=True)
crypto = pd.read_csv('ledger-positions-2021-06-15.csv', skipinitialspace=True)

In [6]:
#for index, row in stocks.iterrows():
#    print(row['symbol'])
#    row['total_cost'] = row['quantity'] * row['unit_cost']
#    row['market_value'] = row['quantity'] * row['last']

In [7]:
portfolio = pd.concat([stocks, crypto])
portfolio['cost'] = portfolio['quantity'] * portfolio['unit_cost']
portfolio['market_value'] = portfolio['quantity'] * portfolio['last']
portfolio['percent_gain'] = 100.0*(portfolio['market_value'] - portfolio['cost'])/portfolio['cost']
total_value = portfolio['market_value'].sum()
total_cost = portfolio['cost'].sum()
total_gain = total_value - total_cost
total_percent_gain = 100.0 * total_gain / total_cost
portfolio['percent_portfolio'] = 100.0*(portfolio['market_value'] - portfolio['cost'])/total_value
portfolio.sort_values(['market_value'], ascending=False, inplace=True, ignore_index=True)

In [8]:
portfolio

,symbol,quantity,last,unit_cost,cost,market_value,percent_gain,percent_portfolio
0,BTC,0.880098,40262.050000,26019.780000,22899.952435,35434.543642,54.736320,6.438218
1,ARKW,225.249830,139.610000,54.128270,12192.383616,31447.128766,157.924371,9.889931
2,ETH,11.273106,2555.150000,1302.680000,14685.249903,28804.477146,96.145638,7.252144
3,IYW,136.481650,95.470000,52.182440,7121.945512,13029.903126,82.954266,3.034540
4,HEX,92275.000000,0.091594,0.011112,1025.393019,8451.879719,724.257583,3.814511
5,LIT,120.124880,69.540000,42.798290,5141.139450,8353.484155,62.483127,1.649976
6,SPHY,269.472850,26.690000,26.328250,7094.748563,7192.230366,1.373999,0.050070
7,MJ,347.911380,20.670000,14.894620,5182.007799,7191.328225,38.774940,1.032059
8,QCLN,100.161130,63.090000,18.064450,1809.355725,6319.165692,249.249493,2.316401
9,GLDM,300.000000,18.500000,18.392600,5517.780000,5550.000000,0.583930,0.016549
10,BP,188.799270,28.380000,38.060630,7185.819160,5358.123283,-25.434760,-0.938770
11,VWO,70.094630,54.510000,53.915540,3779.189828,3820.858281,1.102576,0.021402
12,XLP,49.716350,70.730000,58.146920,2890.852626,3516.437435,21.640149,0.321323
13,ARKG,40.000000,85.550000,94.829000,3793.160000,3422.000000,-9.784981,-0.190641
14,CQQQ,40.000000,80.160000,91.963870,3678.554800,3206.400000,-12.835334,-0.242516
15,TSLA,5.000000,599.360000,56.468000,282.340000,2996.800000,961.415315,1.394245
16,IWR,35.077740,78.710000,74.937550,2628.639895,2760.968915,5.034125,0.067969
17,CCJ,130.000000,20.180000,16.596300,2157.519000,2623.400000,21.593367,0.239293
18,CHIM,100.432930,24.610000,24.921310,2502.920183,2471.654407,-1.249172,-0.016059
19,ARKQ,30.000000,81.030000,87.413000,2622.390000,2430.900000,-7.302118,-0.098356
20,DAL,50.000000,45.530000,40.059800,2002.990000,2276.500000,13.655086,0.140485
21,UAL,40.000000,55.290000,43.729000,1749.160000,2211.600000,26.437833,0.237526
22,CHIL,55.000000,39.190000,43.903640,2414.700200,2155.450000,-10.736331,-0.133160
23,SLV,75.000000,25.650000,25.397740,1904.830500,1923.750000,0.993238,0.009718
24,TLRY,50.000000,17.980000,27.653220,1382.661000,899.000000,-34.980447,-0.248426
25,ADA,540.000000,1.560000,1.560000,842.400000,842.400000,0.000000,0.000000

In [9]:
print('Portfolio value: $%.1fk' % (total_value/1000.))
print('Portfolio cost:  $%.1fk' % (total_cost/1000.))
print('Unrealized gain:   %.1f%%' % (total_percent_gain))

Portfolio value: $194.7k
Portfolio cost:  $124.5k
Unrealized gain:   56.4%

## Update portfolio prices from yfinance

In [61]:
from datetime import datetime
import pytz

# datetime object containing current date and time
now = datetime.now()
 
print("now =", now)

# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S %Z")
print("date and time =", dt_string)

now = 2021-06-16 09:07:59.628477
date and time = 16/06/2021 09:07:59

In [62]:
from datetime import datetime
import pytz

# datetime object containing current date and time
now = datetime.now(pytz.timezone('US/Pacific'))
 
print("now =", now)

# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S %Z")
print("date and time =", dt_string)

now = 2021-06-16 09:08:03.085355-07:00
date and time = 16/06/2021 09:08:03 PDT

In [63]:
dt = datetime(2021, 6, 16, 9, 0, 0, tzinfo=pytz.timezone('US/Eastern'))

In [65]:
fmt = '%Y-%m-%d %H:%M:%S %Z (%z)'
dt.strftime(fmt)

'2021-06-16 09:00:00 LMT (-0456)'

In [56]:
help(datetime.now)

Help on built-in function now:

now(tz=None) method of builtins.type instance
    Returns new datetime object representing current time local to tz.

      tz
        Timezone object.

    If no tz is specified, uses local timezone.

In [57]:
import pytz

In [58]:
help(pytz)

Help on package pytz:

NAME
    pytz

DESCRIPTION
    datetime.tzinfo timezone definitions generated from the
    Olson timezone database:

        ftp://elsie.nci.nih.gov/pub/tz*.tar.gz

    See the datetime section of the Python Library Reference for information
    on how to use these modules.

PACKAGE CONTENTS
    exceptions
    lazy
    reference
    tzfile
    tzinfo

CLASSES
    builtins.KeyError(builtins.LookupError)
        pytz.exceptions.UnknownTimeZoneError(builtins.KeyError, pytz.exceptions.Error)
    datetime.tzinfo(builtins.object)
        pytz.tzinfo.BaseTzInfo
    pytz.exceptions.Error(builtins.Exception)
        pytz.exceptions.InvalidTimeError
            pytz.exceptions.AmbiguousTimeError
            pytz.exceptions.NonExistentTimeError
        pytz.exceptions.UnknownTimeZoneError(builtins.KeyError, pytz.exceptions.Error)

    class AmbiguousTimeError(InvalidTimeError)
     |  Exception raised when attempting to create an ambiguous wallclock time.
     |
     |  At the end of a DST transition period, a particular wallclock time will
     |  occur twice (once before the clocks are set back, once after). Both
     |  possibilities may be correct, unless further information is supplied.
     |
     |  See DstTzInfo.normalize() for more info
     |
     |  Method resolution order:
     |      AmbiguousTimeError
     |      InvalidTimeError
     |      Error
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Data descriptors inherited from Error:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.Exception:
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class BaseTzInfo(datetime.tzinfo)
     |  Abstract base class for time zone info objects.
     |
     |  Method resolution order:
     |      BaseTzInfo
     |      datetime.tzinfo
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __str__(self)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  zone = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from datetime.tzinfo:
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      -> (cls, state)
     |
     |  dst(...)
     |      datetime -> DST offset as timedelta positive east of UTC.
     |
     |  fromutc(...)
     |      datetime in UTC -> datetime in local time.
     |
     |  tzname(...)
     |      datetime -> string name of time zone.
     |
     |  utcoffset(...)
     |      datetime -> timedelta showing offset from UTC, negative values indicating West of UTC
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from datetime.tzinfo:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.

    class InvalidTimeError(Error)
     |  Base class for invalid time exceptions.
     |
     |  Method resolution order:
     |      InvalidTimeError
     |      Error
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Data descriptors inherited from Error:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.Exception:
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class NonExistentTimeError(InvalidTimeError)
     |  Exception raised when attempting to create a wallclock time that
     |  cannot exist.
     |
     |  At the start of a DST transition period, the wallclock time jumps forward.
     |  The instants jumped over never occur.
     |
     |  Method resolution order:
     |      NonExistentTimeError
     |      InvalidTimeError
     |      Error
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Data descriptors inherited from Error:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.Exception:
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class UnknownTimeZoneError(builtins.KeyError, Error)
     |  Exception raised when pytz is passed an unknown timezone.
     |
     |  >>> isinstance(UnknownTimeZoneError(), LookupError)
     |  True
     |
     |  This class is actually a subclass of KeyError to provide backwards
     |  compatibility with code relying on the undocumented behavior of earlier
     |  pytz releases.
     |
     |  >>> isinstance(UnknownTimeZoneError(), KeyError)
     |  True
     |
     |  And also a subclass of pytz.exceptions.Error, as are other pytz
     |  exceptions.
     |
     |  >>> isinstance(UnknownTimeZoneError(), Error)
     |  True
     |
     |  Method resolution order:
     |      UnknownTimeZoneError
     |      builtins.KeyError
     |      builtins.LookupError
     |      Error
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Data descriptors defined here:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.KeyError:
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.LookupError:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

FUNCTIONS
    FixedOffset(offset, _tzinfos={})
        return a fixed-offset timezone based off a number of minutes.

            >>> one = FixedOffset(-330)
            >>> one
            pytz.FixedOffset(-330)
            >>> str(one.utcoffset(datetime.datetime.now()))
            '-1 day, 18:30:00'
            >>> str(one.dst(datetime.datetime.now()))
            '0:00:00'

            >>> two = FixedOffset(1380)
            >>> two
            pytz.FixedOffset(1380)
            >>> str(two.utcoffset(datetime.datetime.now()))
            '23:00:00'
            >>> str(two.dst(datetime.datetime.now()))
            '0:00:00'

        The datetime.timedelta must be between the range of -1 and 1 day,
        non-inclusive.

            >>> FixedOffset(1440)
            Traceback (most recent call last):
            ...
            ValueError: ('absolute offset is too large', 1440)

            >>> FixedOffset(-1440)
            Traceback (most recent call last):
            ...
            ValueError: ('absolute offset is too large', -1440)

        An offset of 0 is special-cased to return UTC.

            >>> FixedOffset(0) is UTC
            True

        There should always be only one instance of a FixedOffset per timedelta.
        This should be true for multiple creation calls.

            >>> FixedOffset(-330) is one
            True
            >>> FixedOffset(1380) is two
            True

        It should also be true for pickling.

            >>> import pickle
            >>> pickle.loads(pickle.dumps(one)) is one
            True
            >>> pickle.loads(pickle.dumps(two)) is two
            True

    timezone(zone)
        Return a datetime.tzinfo implementation for the given timezone

        >>> from datetime import datetime, timedelta
        >>> utc = timezone('UTC')
        >>> eastern = timezone('US/Eastern')
        >>> eastern.zone
        'US/Eastern'
        >>> timezone(unicode('US/Eastern')) is eastern
        True
        >>> utc_dt = datetime(2002, 10, 27, 6, 0, 0, tzinfo=utc)
        >>> loc_dt = utc_dt.astimezone(eastern)
        >>> fmt = '%Y-%m-%d %H:%M:%S %Z (%z)'
        >>> loc_dt.strftime(fmt)
        '2002-10-27 01:00:00 EST (-0500)'
        >>> (loc_dt - timedelta(minutes=10)).strftime(fmt)
        '2002-10-27 00:50:00 EST (-0500)'
        >>> eastern.normalize(loc_dt - timedelta(minutes=10)).strftime(fmt)
        '2002-10-27 01:50:00 EDT (-0400)'
        >>> (loc_dt + timedelta(minutes=10)).strftime(fmt)
        '2002-10-27 01:10:00 EST (-0500)'

        Raises UnknownTimeZoneError if passed an unknown zone.

        >>> try:
        ...     timezone('Asia/Shangri-La')
        ... except UnknownTimeZoneError:
        ...     print('Unknown')
        Unknown

        >>> try:
        ...     timezone(unicode('\N{TRADE MARK SIGN}'))
        ... except UnknownTimeZoneError:
        ...     print('Unknown')
        Unknown

DATA
    __all__ = ['timezone', 'utc', 'country_timezones', 'country_names', 'A...
    all_timezones = ['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis...amo...
    all_timezones_set = LazySet({'HST', 'Asia/Tashkent', 'Asia/Taipei', .....
    common_timezones = ['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis......
    common_timezones_set = LazySet({'Asia/Tashkent', 'Asia/Taipei', 'Antar...
    country_names = <pytz._CountryNameDict object>
    country_timezones = <pytz._CountryTimezoneDict object>
    utc = <UTC>

VERSION
    2021.1

FILE
    /home/ryan/at-github/statistics-notebooks/env1/lib/python3.8/site-packages/pytz/__init__.py

In [59]:
pytz.common_timezones

['Africa/Abidjan',
 'Africa/Accra',
 'Africa/Addis_Ababa',
 'Africa/Algiers',
 'Africa/Asmara',
 'Africa/Bamako',
 'Africa/Bangui',
 'Africa/Banjul',
 'Africa/Bissau',
 'Africa/Blantyre',
 'Africa/Brazzaville',
 'Africa/Bujumbura',
 'Africa/Cairo',
 'Africa/Casablanca',
 'Africa/Ceuta',
 'Africa/Conakry',
 'Africa/Dakar',
 'Africa/Dar_es_Salaam',
 'Africa/Djibouti',
 'Africa/Douala',
 'Africa/El_Aaiun',
 'Africa/Freetown',
 'Africa/Gaborone',
 'Africa/Harare',
 'Africa/Johannesburg',
 'Africa/Juba',
 'Africa/Kampala',
 'Africa/Khartoum',
 'Africa/Kigali',
 'Africa/Kinshasa',
 'Africa/Lagos',
 'Africa/Libreville',
 'Africa/Lome',
 'Africa/Luanda',
 'Africa/Lubumbashi',
 'Africa/Lusaka',
 'Africa/Malabo',
 'Africa/Maputo',
 'Africa/Maseru',
 'Africa/Mbabane',
 'Africa/Mogadishu',
 'Africa/Monrovia',
 'Africa/Nairobi',
 'Africa/Ndjamena',
 'Africa/Niamey',
 'Africa/Nouakchott',
 'Africa/Ouagadougou',
 'Africa/Porto-Novo',
 'Africa/Sao_Tome',
 'Africa/Tripoli',
 'Africa/Tunis',
 'Africa/Windhoek',
 'America/Adak',
 'America/Anchorage',
 'America/Anguilla',
 'America/Antigua',
 'America/Araguaina',
 'America/Argentina/Buenos_Aires',
 'America/Argentina/Catamarca',
 'America/Argentina/Cordoba',
 'America/Argentina/Jujuy',
 'America/Argentina/La_Rioja',
 'America/Argentina/Mendoza',
 'America/Argentina/Rio_Gallegos',
 'America/Argentina/Salta',
 'America/Argentina/San_Juan',
 'America/Argentina/San_Luis',
 'America/Argentina/Tucuman',
 'America/Argentina/Ushuaia',
 'America/Aruba',
 'America/Asuncion',
 'America/Atikokan',
 'America/Bahia',
 'America/Bahia_Banderas',
 'America/Barbados',
 'America/Belem',
 'America/Belize',
 'America/Blanc-Sablon',
 'America/Boa_Vista',
 'America/Bogota',
 'America/Boise',
 'America/Cambridge_Bay',
 'America/Campo_Grande',
 'America/Cancun',
 'America/Caracas',
 'America/Cayenne',
 'America/Cayman',
 'America/Chicago',
 'America/Chihuahua',
 'America/Costa_Rica',
 'America/Creston',
 'America/Cuiaba',
 'America/Curacao',
 'America/Danmarkshavn',
 'America/Dawson',
 'America/Dawson_Creek',
 'America/Denver',
 'America/Detroit',
 'America/Dominica',
 'America/Edmonton',
 'America/Eirunepe',
 'America/El_Salvador',
 'America/Fort_Nelson',
 'America/Fortaleza',
 'America/Glace_Bay',
 'America/Goose_Bay',
 'America/Grand_Turk',
 'America/Grenada',
 'America/Guadeloupe',
 'America/Guatemala',
 'America/Guayaquil',
 'America/Guyana',
 'America/Halifax',
 'America/Havana',
 'America/Hermosillo',
 'America/Indiana/Indianapolis',
 'America/Indiana/Knox',
 'America/Indiana/Marengo',
 'America/Indiana/Petersburg',
 'America/Indiana/Tell_City',
 'America/Indiana/Vevay',
 'America/Indiana/Vincennes',
 'America/Indiana/Winamac',
 'America/Inuvik',
 'America/Iqaluit',
 'America/Jamaica',
 'America/Juneau',
 'America/Kentucky/Louisville',
 'America/Kentucky/Monticello',
 'America/Kralendijk',
 'America/La_Paz',
 'America/Lima',
 'America/Los_Angeles',
 'America/Lower_Princes',
 'America/Maceio',
 'America/Managua',
 'America/Manaus',
 'America/Marigot',
 'America/Martinique',
 'America/Matamoros',
 'America/Mazatlan',
 'America/Menominee',
 'America/Merida',
 'America/Metlakatla',
 'America/Mexico_City',
 'America/Miquelon',
 'America/Moncton',
 'America/Monterrey',
 'America/Montevideo',
 'America/Montserrat',
 'America/Nassau',
 'America/New_York',
 'America/Nipigon',
 'America/Nome',
 'America/Noronha',
 'America/North_Dakota/Beulah',
 'America/North_Dakota/Center',
 'America/North_Dakota/New_Salem',
 'America/Nuuk',
 'America/Ojinaga',
 'America/Panama',
 'America/Pangnirtung',
 'America/Paramaribo',
 'America/Phoenix',
 'America/Port-au-Prince',
 'America/Port_of_Spain',
 'America/Porto_Velho',
 'America/Puerto_Rico',
 'America/Punta_Arenas',
 'America/Rainy_River',
 'America/Rankin_Inlet',
 'America/Recife',
 'America/Regina',
 'America/Resolute',
 'America/Rio_Branco',
 'America/Santarem',
 'America/Santiago',
 'America/Santo_Domingo',
 'America/Sao_Paulo',
 'America/Scoresbysund',
 'America/Sitka',
 'America/St_Barthelemy',
 'America/St_Johns',
 'America/St_Kitts',
 'America/St_Lucia',
 'America/St_Thomas',
 'America/St_Vincent',
 'America/Swift_Current',
 'America/Tegucigalpa',
 'America/Thule',
 'America/Thunder_Bay',
 'America/Tijuana',
 'America/Toronto',
 'America/Tortola',
 'America/Vancouver',
 'America/Whitehorse',
 'America/Winnipeg',
 'America/Yakutat',
 'America/Yellowknife',
 'Antarctica/Casey',
 'Antarctica/Davis',
 'Antarctica/DumontDUrville',
 'Antarctica/Macquarie',
 'Antarctica/Mawson',
 'Antarctica/McMurdo',
 'Antarctica/Palmer',
 'Antarctica/Rothera',
 'Antarctica/Syowa',
 'Antarctica/Troll',
 'Antarctica/Vostok',
 'Arctic/Longyearbyen',
 'Asia/Aden',
 'Asia/Almaty',
 'Asia/Amman',
 'Asia/Anadyr',
 'Asia/Aqtau',
 'Asia/Aqtobe',
 'Asia/Ashgabat',
 'Asia/Atyrau',
 'Asia/Baghdad',
 'Asia/Bahrain',
 'Asia/Baku',
 'Asia/Bangkok',
 'Asia/Barnaul',
 'Asia/Beirut',
 'Asia/Bishkek',
 'Asia/Brunei',
 'Asia/Chita',
 'Asia/Choibalsan',
 'Asia/Colombo',
 'Asia/Damascus',
 'Asia/Dhaka',
 'Asia/Dili',
 'Asia/Dubai',
 'Asia/Dushanbe',
 'Asia/Famagusta',
 'Asia/Gaza',
 'Asia/Hebron',
 'Asia/Ho_Chi_Minh',
 'Asia/Hong_Kong',
 'Asia/Hovd',
 'Asia/Irkutsk',
 'Asia/Jakarta',
 'Asia/Jayapura',
 'Asia/Jerusalem',
 'Asia/Kabul',
 'Asia/Kamchatka',
 'Asia/Karachi',
 'Asia/Kathmandu',
 'Asia/Khandyga',
 'Asia/Kolkata',
 'Asia/Krasnoyarsk',
 'Asia/Kuala_Lumpur',
 'Asia/Kuching',
 'Asia/Kuwait',
 'Asia/Macau',
 'Asia/Magadan',
 'Asia/Makassar',
 'Asia/Manila',
 'Asia/Muscat',
 'Asia/Nicosia',
 'Asia/Novokuznetsk',
 'Asia/Novosibirsk',
 'Asia/Omsk',
 'Asia/Oral',
 'Asia/Phnom_Penh',
 'Asia/Pontianak',
 'Asia/Pyongyang',
 'Asia/Qatar',
 'Asia/Qostanay',
 'Asia/Qyzylorda',
 'Asia/Riyadh',
 'Asia/Sakhalin',
 'Asia/Samarkand',
 'Asia/Seoul',
 'Asia/Shanghai',
 'Asia/Singapore',
 'Asia/Srednekolymsk',
 'Asia/Taipei',
 'Asia/Tashkent',
 'Asia/Tbilisi',
 'Asia/Tehran',
 'Asia/Thimphu',
 'Asia/Tokyo',
 'Asia/Tomsk',
 'Asia/Ulaanbaatar',
 'Asia/Urumqi',
 'Asia/Ust-Nera',
 'Asia/Vientiane',
 'Asia/Vladivostok',
 'Asia/Yakutsk',
 'Asia/Yangon',
 'Asia/Yekaterinburg',
 'Asia/Yerevan',
 'Atlantic/Azores',
 'Atlantic/Bermuda',
 'Atlantic/Canary',
 'Atlantic/Cape_Verde',
 'Atlantic/Faroe',
 'Atlantic/Madeira',
 'Atlantic/Reykjavik',
 'Atlantic/South_Georgia',
 'Atlantic/St_Helena',
 'Atlantic/Stanley',
 'Australia/Adelaide',
 'Australia/Brisbane',
 'Australia/Broken_Hill',
 'Australia/Darwin',
 'Australia/Eucla',
 'Australia/Hobart',
 'Australia/Lindeman',
 'Australia/Lord_Howe',
 'Australia/Melbourne',
 'Australia/Perth',
 'Australia/Sydney',
 'Canada/Atlantic',
 'Canada/Central',
 'Canada/Eastern',
 'Canada/Mountain',
 'Canada/Newfoundland',
 'Canada/Pacific',
 'Europe/Amsterdam',
 'Europe/Andorra',
 'Europe/Astrakhan',
 'Europe/Athens',
 'Europe/Belgrade',
 'Europe/Berlin',
 'Europe/Bratislava',
 'Europe/Brussels',
 'Europe/Bucharest',
 'Europe/Budapest',
 'Europe/Busingen',
 'Europe/Chisinau',
 'Europe/Copenhagen',
 'Europe/Dublin',
 'Europe/Gibraltar',
 'Europe/Guernsey',
 'Europe/Helsinki',
 'Europe/Isle_of_Man',
 'Europe/Istanbul',
 'Europe/Jersey',
 'Europe/Kaliningrad',
 'Europe/Kiev',
 'Europe/Kirov',
 'Europe/Lisbon',
 'Europe/Ljubljana',
 'Europe/London',
 'Europe/Luxembourg',
 'Europe/Madrid',
 'Europe/Malta',
 'Europe/Mariehamn',
 'Europe/Minsk',
 'Europe/Monaco',
 'Europe/Moscow',
 'Europe/Oslo',
 'Europe/Paris',
 'Europe/Podgorica',
 'Europe/Prague',
 'Europe/Riga',
 'Europe/Rome',
 'Europe/Samara',
 'Europe/San_Marino',
 'Europe/Sarajevo',
 'Europe/Saratov',
 'Europe/Simferopol',
 'Europe/Skopje',
 'Europe/Sofia',
 'Europe/Stockholm',
 'Europe/Tallinn',
 'Europe/Tirane',
 'Europe/Ulyanovsk',
 'Europe/Uzhgorod',
 'Europe/Vaduz',
 'Europe/Vatican',
 'Europe/Vienna',
 'Europe/Vilnius',
 'Europe/Volgograd',
 'Europe/Warsaw',
 'Europe/Zagreb',
 'Europe/Zaporozhye',
 'Europe/Zurich',
 'GMT',
 'Indian/Antananarivo',
 'Indian/Chagos',
 'Indian/Christmas',
 'Indian/Cocos',
 'Indian/Comoro',
 'Indian/Kerguelen',
 'Indian/Mahe',
 'Indian/Maldives',
 'Indian/Mauritius',
 'Indian/Mayotte',
 'Indian/Reunion',
 'Pacific/Apia',
 'Pacific/Auckland',
 'Pacific/Bougainville',
 'Pacific/Chatham',
 'Pacific/Chuuk',
 'Pacific/Easter',
 'Pacific/Efate',
 'Pacific/Enderbury',
 'Pacific/Fakaofo',
 'Pacific/Fiji',
 'Pacific/Funafuti',
 'Pacific/Galapagos',
 'Pacific/Gambier',
 'Pacific/Guadalcanal',
 'Pacific/Guam',
 'Pacific/Honolulu',
 'Pacific/Kiritimati',
 'Pacific/Kosrae',
 'Pacific/Kwajalein',
 'Pacific/Majuro',
 'Pacific/Marquesas',
 'Pacific/Midway',
 'Pacific/Nauru',
 'Pacific/Niue',
 'Pacific/Norfolk',
 'Pacific/Noumea',
 'Pacific/Pago_Pago',
 'Pacific/Palau',
 'Pacific/Pitcairn',
 'Pacific/Pohnpei',
 'Pacific/Port_Moresby',
 'Pacific/Rarotonga',
 'Pacific/Saipan',
 'Pacific/Tahiti',
 'Pacific/Tarawa',
 'Pacific/Tongatapu',
 'Pacific/Wake',
 'Pacific/Wallis',
 'US/Alaska',
 'US/Arizona',
 'US/Central',
 'US/Eastern',
 'US/Hawaii',
 'US/Mountain',
 'US/Pacific',
 'UTC']

In [40]:
def transform_symbol(s):
    d = {
        'ADA': 'ADA-USD',
        'BTC': 'BTC-USD',
        'ETH': 'ETH-USD',
        'HEX': 'HEX-USD',
    }
    return d.get(s, s)

In [41]:
symbols = [ transform_symbol(s) for s in portfolio['symbol'] ]

In [42]:
symbols

['BTC-USD',
 'ARKW',
 'ETH-USD',
 'IYW',
 'HEX-USD',
 'LIT',
 'SPHY',
 'MJ',
 'QCLN',
 'GLDM',
 'BP',
 'VWO',
 'XLP',
 'ARKG',
 'CQQQ',
 'TSLA',
 'IWR',
 'CCJ',
 'CHIM',
 'ARKQ',
 'DAL',
 'UAL',
 'CHIL',
 'SLV',
 'TLRY',
 'ADA-USD']

In [70]:
data = yf.download(tickers=symbols[:3], period='1d', interval='15m', group_by='ticker')

[*********************100%***********************]  3 of 3 completed

In [69]:
#data = yf.download(tickers=symbols[:3], interval='15m', group_by='ticker', start=datetime(2021, 6, 16, 9, 0, 0, tzinfo=pytz.timezone('US/Eastern')), end=datetime(2021, 6, 16, 12, 0, 0, tzinfo=pytz.timezone('US/Eastern')))

[*********************100%***********************]  3 of 3 completed

3 Failed downloads:
- ETH-USD: Data doesn't exist for startDate = 1623862800, endDate = 1623873600
- ARKW: Data doesn't exist for startDate = 1623862800, endDate = 1623873600
- BTC-USD: Data doesn't exist for startDate = 1623862800, endDate = 1623873600

In [71]:
data['ARKW']

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-15 23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-15 23:15:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-15 23:30:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-15 23:45:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-16 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2021-06-16 15:45:00+00:00,139.770004,139.929993,139.580002,139.619995,139.619995,7387.0
2021-06-16 16:00:00+00:00,139.684998,139.684998,138.972000,138.972000,138.972000,7737.0
2021-06-16 16:15:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-16 16:17:02+00:00,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-16 16:17:35+00:00,139.067596,139.067596,139.067596,139.067596,139.067596,0.0

In [50]:
help(yf.download)

Help on function download in module yfinance.multi:

download(tickers, start=None, end=None, actions=False, threads=True, group_by='column', auto_adjust=False, back_adjust=False, progress=True, period='max', interval='1d', prepost=False, proxy=None, rounding=False, **kwargs)
    Download yahoo tickers
    :Parameters:
        tickers : str, list
            List of tickers to download
        period : str
            Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
            Either Use period parameter or use start and end
        interval : str
            Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
            Intraday data cannot extend last 60 days
        start: str
            Download start date string (YYYY-MM-DD) or _datetime.
            Default is 1900-01-01
        end: str
            Download end date string (YYYY-MM-DD) or _datetime.
            Default is now
        group_by : str
            Group by 'ticker' or 'column' (default)
        prepost : bool
            Include Pre and Post market data in results?
            Default is False
        auto_adjust: bool
            Adjust all OHLC automatically? Default is False
        actions: bool
            Download dividend + stock splits data. Default is False
        threads: bool / int
            How many threads to use for mass downloading. Default is True
        proxy: str
            Optional. Proxy server URL scheme. Default is None
        rounding: bool
            Optional. Round values to 2 decimal places?

In [33]:
test = yf.download(tickers='CHIL.NYSEArca', period='1d', interval='15m')

[*********************100%***********************]  1 of 1 completed

1 Failed download:
- CHIL.NYSEARCA: No data found, symbol may be delisted

In [28]:
test

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [38]:
msft = yf.Ticker('CHIL')

In [39]:
msft.info

{'previousClose': 39.1923,
 'regularMarketOpen': 38.92,
 'twoHundredDayAverage': 40.374035,
 'trailingAnnualDividendYield': None,
 'payoutRatio': None,
 'volume24Hr': None,
 'regularMarketDayHigh': 38.92,
 'navPrice': 39.58,
 'averageDailyVolume10Day': 1014,
 'totalAssets': 13072958,
 'regularMarketPreviousClose': 39.1923,
 'fiftyDayAverage': 38.932655,
 'trailingAnnualDividendRate': None,
 'open': 38.92,
 'toCurrency': None,
 'averageVolume10days': 1014,
 'expireDate': None,
 'yield': 0.0093,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 38.69,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 667,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': None,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 3589,
 'priceToSalesTrailing12Months': None,
 'dayLow': 38.69,
 'ask': 38.98,
 'ytdReturn': None,
 'askSize': 1300,
 'volume': 667,
 'fiftyTwoWeekHigh': 48.635,
 'forwardPE': None,
 'maxAge': 1,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 29.63,
 'bid': 38.69,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 800,
 'dayHigh': 38.92,
 'exchange': 'PCX',
 'shortName': 'Global X Funds Global X MSCI Ch',
 'longName': 'Global X MSCI China Large-Cap 50 ETF',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'ETF',
 'symbol': 'CHIL',
 'messageBoardId': 'finmb_581837348',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': None,
 'beta3Year': 0,
 'profitMargins': None,
 'enterpriseToEbitda': None,
 '52WeekChange': None,
 'morningStarRiskRating': None,
 'forwardEps': None,
 'revenueQuarterlyGrowth': None,
 'fundInceptionDate': 1544140800,
 'annualReportExpenseRatio': None,
 'bookValue': None,
 'fundFamily': 'Global X Funds',
 'lastFiscalYearEnd': None,
 'netIncomeToCommon': None,
 'trailingEps': None,
 'lastDividendValue': None,
 'SandP52WeekChange': None,
 'priceToBook': None,
 'nextFiscalYearEnd': None,
 'mostRecentQuarter': None,
 'enterpriseValue': None,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': 'Exchange Traded Fund',
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': None,
 'pegRatio': None,
 'lastCapGain': None,
 'category': 'China Region',
 'fiveYearAverageReturn': None,
 'phone': '888-493-8631',
 'longBusinessSummary': 'The investment seeks to provide investment results that correspond generally to the price and yield performance, before fees and expenses, of the MSCI China Top 50 Select Index.\n The fund invests at least 80% of its total assets in the securities of the underlying index and in ADRs and GDRs based on the securities in the underlying index. The underlying index is designed to select the 50 largest equity securities, by free-float market capitalization, of the eligible China equity universe, as defined by the index provider. The fund is non-diversified.',
 'companyOfficers': [],
 'regularMarketPrice': 38.69,
 'logo_url': ''}

In [37]:
msft.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
...               ...           ...
2020-05-20       0.51           0.0
2020-08-19       0.51           0.0
2020-11-18       0.56           0.0
2021-02-17       0.56           0.0
2021-05-19       0.56           0.0

[79 rows x 2 columns]

In [11]:
data

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-16 09:30:00-04:00,139.080002,140.160004,138.779999,140.139999,140.139999,119713
2021-06-16 09:45:00-04:00,140.130005,140.229996,139.509995,139.699997,139.699997,27846
2021-06-16 10:00:00-04:00,139.774994,140.470001,139.580002,140.369995,140.369995,17557
2021-06-16 10:15:00-04:00,140.449997,140.669998,140.270004,140.300003,140.300003,11572
2021-06-16 10:30:00-04:00,140.300003,140.300003,139.910004,140.199997,140.199997,22332
2021-06-16 10:45:00-04:00,139.830002,139.876694,139.830002,139.876694,139.876694,3551
2021-06-16 10:49:30-04:00,139.770004,139.770004,139.770004,139.770004,139.770004,0

In [14]:
data['Close'][-1]

139.77000427246094